### ISSUE TITLE
Move buttons B & A

### ISSUE THREAD

**Issue by rdpowers** [CCHS-Melbourne/IoTuz#22]
To my hands the B & A buttons are too close to the edge. They are about the right height. Suggest move left 5mm and down maybe slightly.

**Comment by rdpowers** [comment]
Doing more measurements, I'd say left 5mm and increase vertical spacing by 3-5mm while keeping the vertical center of the buttons the same (move B down by 1.5-2.5mm/A up by 1.5-2.5mm). Horizontal spacing could increase too, but I'd rather have that A button more to the left than anything.

**Comment by mage0r** [comment]
Fixed in e62c2e9 I hope.
