### ISSUE TITLE
Bigger drills

### ISSUE THREAD

**Issue by mage0r** [CCHS-Melbourne/IoTuz#5]
For speaker (just fits).
For rotary encoder (doesn't fit signal pins)
APA106 (increase spacing)

**Comment by mage0r** [comment]
Fixed spacing on APA106 footprint in 2107f38

**Comment by mage0r** [comment]
Fixed hole sizes for encoder in 8cdbe23

**Comment by rdpowers** [comment]
Add bigger pads around TH parts where possible to make hand-soldering easier. It's pretty small on the speaker, encoder, IRTx, & APA106. Wouldn't hurt to do it on all of the TH stuff though.

**Comment by mage0r** [comment]
I've increased the pads on the speaker and the rotary encoder ones are already fairly big.  I can't do much about the apa106, it's pins are fairly close together and if I make the pads much larger we'll have problems with bridging.

**Comment by rdpowers** [comment]
Did you increase the spacing of the APA106 pins? On second thought, this is probably not a good idea - they probably should have been closer if possible, or left alone if not.

**Comment by mage0r** [comment]
I reduced them, but I haven't updated the PCB.  Same with the other footprints, They've been corrected in the kicad_mod files, but the change hasn't gone through the PCB yet.

**Comment by mage0r** [comment]
Updated the pcb in e62c2e9
